import dayjs from "dayjs";

const locale = {
  name: "ain-latn",
  weekdays: "日曜日_月曜日_火曜日_水曜日_木曜日_金曜日_土曜日".split("_"),
  weekdaysShort: "日_月_火_水_木_金_土".split("_"),
  weekdaysMin: "日_月_火_水_木_金_土".split("_"),
  months: [
    "1-cup",
    "2-cup",
    "3-cup",
    "4-cup",
    "5-cup",
    "6-cup",
    "7-cup",
    "8-cup",
    "9-cup",
    "10-cup",
    "11-cup",
    "12-cup",
  ],
  monthsShort: [
    "1-cup",
    "2-cup",
    "3-cup",
    "4-cup",
    "5-cup",
    "6-cup",
    "7-cup",
    "8-cup",
    "9-cup",
    "10-cup",
    "11-cup",
    "12-cup",
  ],
  ordinal: (n: number) => `${n}-to`,
  formats: {
    LT: "HH:mm",
    LTS: "HH:mm:ss",
    L: "YYYY/MM/DD",
    LL: "YYYY-[pa] M-cup D-to",
    LLL: "YYYY-[pa] M-cup D-to HH:mm",
    LLLL: "YYYY-[pa] M-cup D-to dddd HH:mm",
    l: "YYYY/MM/DD",
    ll: "YYYY-[pa] M-cup D-to",
    lll: "YYYY-[pa] M-cup D-to HH:mm",
    llll: "YYYY-[pa] M-cup D-to (ddd) HH:mm",
  },
  meridiem: (hour: number) => (hour < 12 ? "午前" : "午後"),
  relativeTime: {
    future: "%s okake",
    past: "%s etok",
    s: "数秒",
    m: "1-pun",
    mm: "%d-pun",
    h: "1-icicikan",
    hh: "%d-icicikan",
    d: "1-to",
    dd: "%d-to",
    M: "1-cup",
    MM: "%d-cup",
    y: "1-pa",
    yy: "%d-pa",
  },
};

dayjs.locale(locale, undefined, true);

export default locale;
