import dayjs from "dayjs";

const locale = {
  name: "ain-kana",
  weekdays: "日曜日_月曜日_火曜日_水曜日_木曜日_金曜日_土曜日".split("_"),
  weekdaysShort: "日_月_火_水_木_金_土".split("_"),
  weekdaysMin: "日_月_火_水_木_金_土".split("_"),
  months: [
    "トウェタンネ",
    "クウェカイ",
    "キウタチュㇷ゚",
    "モチュㇷ゚",
    "シンチチュㇷ゚",
    "マウタチュㇷ゚",
    "マウチチュㇷ゚",
    "ハㇷ゚ラㇷ゚",
    "ニホラㇰ",
    "ウレポㇰ",
    "ルウェカリチュㇷ゚",
    "チュルㇷ゚",
  ],
  monthsShort: [
    "トウェタンネ",
    "クウェカイ",
    "キウタチュㇷ゚",
    "モチュㇷ゚",
    "シンチチュㇷ゚",
    "マウタチュㇷ゚",
    "マウチチュㇷ゚",
    "ハㇷ゚ラㇷ゚",
    "ニホラㇰ",
    "ウレポㇰ",
    "ルウェカリチュㇷ゚",
    "チュルㇷ゚",
  ],
  ordinal: (n: number) => `${n}ト`,
  formats: {
    LT: "HH:mm",
    LTS: "HH:mm:ss",
    L: "YYYY/MM/DD",
    LL: "YYYYパ　MMMM　Dト",
    LLL: "YYYYパ　MMMM　Dト　HH:mm",
    LLLL: "YYYYパ　MMMM　Dト　dddd HH:mm",
    l: "YYYY/MM/DD",
    ll: "YYYYパ　MMMM　Dト",
    lll: "YYYYパ　MMMM　Dト　HH:mm",
    llll: "YYYYパ　MMMM　Dト　(ddd) HH:mm",
  },
  meridiem: (hour: number) => (hour < 12 ? "午前" : "午後"),
  relativeTime: {
    future: "%s　オカケ",
    past: "%s エトㇰ",
    s: "数秒",
    m: "1プン",
    mm: "%dプン",
    h: "1イチチカン",
    hh: "%dイチチカン",
    d: "1ト",
    dd: "%dト",
    M: "1チュㇷ゚",
    MM: "%dチュㇷ゚",
    y: "1パ",
    yy: "%dパ",
  },
};

dayjs.locale(locale, undefined, true);

export default locale;
