import dayjs from "dayjs";

const locale = {
  name: "ain-latn",
  weekdays: "日曜日_月曜日_火曜日_水曜日_木曜日_金曜日_土曜日".split("_"),
  weekdaysShort: "日_月_火_水_木_金_土".split("_"),
  weekdaysMin: "日_月_火_水_木_金_土".split("_"),
  months: [
    "toetanne",
    "kuekay",
    "kiwtacup",
    "mocup",
    "sincicup",
    "mawtacup",
    "mawcicup",
    "haprap",
    "nihorak",
    "urepok",
    "ruekaricup",
    "turup",
  ],
  monthsShort: [
    "toetanne",
    "kuekay",
    "kiwtacup",
    "mocup",
    "sincicup",
    "mawtacup",
    "mawcicup",
    "haprap",
    "nihorak",
    "urepok",
    "ruekaricup",
    "turup",
  ],
  ordinal: (n: number) => `${n}-to`,
  formats: {
    LT: "HH:mm",
    LTS: "HH:mm:ss",
    L: "YYYY/MM/DD",
    LL: "YYYY-[pa] MMMM D-to",
    LLL: "YYYY-[pa] MMMM D-to HH:mm",
    LLLL: "YYYY-[pa] MMMM D-to dddd HH:mm",
    l: "YYYY/MM/DD",
    ll: "YYYY-[pa] MMMM D-to",
    lll: "YYYY-[pa] MMMM D-to HH:mm",
    llll: "YYYY-[pa] MMMM D-to (ddd) HH:mm",
  },
  meridiem: (hour: number) => (hour < 12 ? "午前" : "午後"),
  relativeTime: {
    future: "%s okake",
    past: "%s etok",
    s: "数秒",
    m: "1-pun",
    mm: "%d-pun",
    h: "1-icicikan",
    hh: "%d-icicikan",
    d: "1-to",
    dd: "%d-to",
    M: "1-cup",
    MM: "%d-cup",
    y: "1-pa",
    yy: "%d-pa",
  },
};

dayjs.locale(locale, undefined, true);

export default locale;
