import dayjs from "dayjs";

const locale = {
  name: "ain-kana",
  weekdays: "日曜日_月曜日_火曜日_水曜日_木曜日_金曜日_土曜日".split("_"),
  weekdaysShort: "日_月_火_水_木_金_土".split("_"),
  weekdaysMin: "日_月_火_水_木_金_土".split("_"),
  months: [
    "1チュㇷ゚",
    "2チュㇷ゚",
    "3チュㇷ゚",
    "4チュㇷ゚",
    "5チュㇷ゚",
    "6チュㇷ゚",
    "7チュㇷ゚",
    "8チュㇷ゚",
    "9チュㇷ゚",
    "10チュㇷ゚",
    "11チュㇷ゚",
    "12チュㇷ゚",
  ],
  monthsShort: [
    "1チュㇷ゚",
    "2チュㇷ゚",
    "3チュㇷ゚",
    "4チュㇷ゚",
    "5チュㇷ゚",
    "6チュㇷ゚",
    "7チュㇷ゚",
    "8チュㇷ゚",
    "9チュㇷ゚",
    "10チュㇷ゚",
    "11チュㇷ゚",
    "12チュㇷ゚",
  ],
  ordinal: (n: number) => `${n}ト`,
  formats: {
    LT: "HH:mm",
    LTS: "HH:mm:ss",
    L: "YYYY/MM/DD",
    LL: "YYYYパ　Mチュㇷ゚　Dト",
    LLL: "YYYYパ　Mチュㇷ゚　Dト　HH:mm",
    LLLL: "YYYYパ　Mチュㇷ゚　Dト　dddd HH:mm",
    l: "YYYY/MM/DD",
    ll: "YYYYパ　Mチュㇷ゚　Dト",
    lll: "YYYYパ　Mチュㇷ゚　Dト　HH:mm",
    llll: "YYYYパ　Mチュㇷ゚　Dト　(ddd) HH:mm",
  },
  meridiem: (hour: number) => (hour < 12 ? "午前" : "午後"),
  relativeTime: {
    future: "%s　オカケ",
    past: "%s エトㇰ",
    s: "数秒",
    m: "1プン",
    mm: "%dプン",
    h: "1イチチカン",
    hh: "%dイチチカン",
    d: "1ト",
    dd: "%dト",
    M: "1チュㇷ゚",
    MM: "%dチュㇷ゚",
    y: "1パ",
    yy: "%dパ",
  },
};

dayjs.locale(locale, undefined, true);

export default locale;
