import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootProps = {
  children: React.ReactNode;
}

export default function RootLayout(props: RootProps) {
  const { children } = props;

  return (
    <html lang="ja">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
